### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by Dingxiangtao** [lyhnsn/GLOTS#5]
作者你好，我想问一下下载完vaihingen数据集中的两个文件后，应该怎么做？我跟着链接中的过程做为什么无法对该数据进行划分，生成的文件夹是空的。期待您的回复

**Comment by lyhnsn** [comment]
Hello. There may be many possible reasons.
Ensure you download the correct file (carefully examine the file name), and mind that DO NOT unzip the zip file. Directly process it.

**Comment by Dingxiangtao** [comment]
Thank you for your reply. I previously decompressed the file which caused the above issue, but now it has been successfully partitioned. Also, is it normal for the images in ann_dir to be completely black now

**Comment by Dingxiangtao** [comment]
Currently, the link to the pre trained model cannot be redirected

**Comment by lyhnsn** [comment]
The authors of BeiT have moved the link. I would update the link after uploading the model to google drive.
